/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_floo_WRAP_H_
#define SWIG_floo_WRAP_H_

class SwigDirector_BMXNetworkListener : public floo::BMXNetworkListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXNetworkListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXNetworkListener();
    virtual void onNetworkChanged(floo::BMXNetworkType type, bool reconnect);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_BMXChatServiceListener : public floo::BMXChatServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXChatServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXChatServiceListener();
    virtual void onStatusChanged(floo::BMXMessagePtr msg, floo::BMXErrorCode error);
    virtual void onAttachmentUploadProgressChanged(floo::BMXMessagePtr msg, int percent);
    virtual void onRecallStatusChanged(floo::BMXMessagePtr msg, floo::BMXErrorCode error);
    virtual void onReceive(floo::BMXMessageList const &list);
    virtual void onReceiveCommandMessages(floo::BMXMessageList const &list);
    virtual void onReceiveSystemMessages(floo::BMXMessageList const &list);
    virtual void onReceiveReadAcks(floo::BMXMessageList const &list);
    virtual void onReceiveDeliverAcks(floo::BMXMessageList const &list);
    virtual void onReceiveRecallMessages(floo::BMXMessageList const &list);
    virtual void onReceiveReadCancels(floo::BMXMessageList const &list);
    virtual void onReceiveReadAllMessages(floo::BMXMessageList const &list);
    virtual void onReceiveDeleteMessages(floo::BMXMessageList const &list);
    virtual void onReceivePlayAcks(floo::BMXMessageList const &list);
    virtual void onAttachmentStatusChanged(floo::BMXMessagePtr msg, floo::BMXErrorCode error, int percent);
    virtual void onAttachmentDownloadByUrlStatusChanged(int64_t msgId, floo::BMXErrorCode error, int percent);
    virtual void onRetrieveHistoryMessages(floo::BMXConversationPtr conversation);
    virtual void onLoadAllConversation();
    virtual void onConversationCreate(floo::BMXConversationPtr conversation, floo::BMXMessagePtr msg);
    virtual void onConversationDelete(int64_t conversationId, floo::BMXErrorCode error);
    virtual void onTotalUnreadCountChanged(int unreadCount);
public:
    bool swig_overrides(int n) {
      return (n < 20 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<20> swig_override;
};

class SwigDirector_BMXPushServiceListener : public floo::BMXPushServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXPushServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXPushServiceListener();
    virtual void onPushStart(std::string const bmxToken);
    virtual void onPushStop();
    virtual void onCertRetrieved(std::string const cert);
    virtual void onSetTags(std::string const &operationId);
    virtual void onGetTags(std::string const &operationId);
    virtual void onDeleteTags(std::string const &operationId);
    virtual void onClearTags(std::string const &operationId);
    virtual void onReceivePush(floo::BMXMessageList const &list);
    virtual void onStatusChanged(floo::BMXMessagePtr msg, floo::BMXErrorCode error);
public:
    bool swig_overrides(int n) {
      return (n < 9 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<9> swig_override;
};

class SwigDirector_BMXRTCEngineListener : public floo::BMXRTCEngineListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXRTCEngineListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXRTCEngineListener();
    virtual void onJoinRoom(std::string const &info, int64_t roomId, floo::BMXErrorCode error);
    virtual void onLeaveRoom(std::string const &info, int64_t roomId, floo::BMXErrorCode error, std::string const &reason);
    virtual void onRejoining(int64_t roomId, floo::BMXErrorCode error);
    virtual void onReJoinRoom(std::string const &info, int64_t roomId, floo::BMXErrorCode error);
    virtual void onMemberJoined(int64_t roomId, int64_t usedId);
    virtual void onMemberExited(int64_t roomId, int64_t usedId, std::string const &reason);
    virtual void onLocalPublish(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onLocalUnPublish(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onRemotePublish(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onRemoteUnPublish(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onSubscribe(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onUnSubscribe(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
    virtual void onRemoteTrackNotify(floo::BMXStreamPtr stream, floo::BMXTrackType trackType, std::string const &info, floo::BMXErrorCode error);
    virtual void onLocalStreamMuteRsp(floo::BMXStreamPtr stream, floo::BMXTrackType trackType, bool mute, std::string const &info, floo::BMXErrorCode error);
    virtual void onRemoteStreamMuteRsp(floo::BMXStreamPtr stream, floo::BMXTrackType trackType, bool mute, std::string const &info, floo::BMXErrorCode error);
    virtual void onSendRTCStats(floo::BMXStreamStatsPtr streamStats, std::string const &info, floo::BMXErrorCode error);
    virtual void onRemoteRTCStats(floo::BMXStreamStatsPtr streamStats, std::string const &info, floo::BMXErrorCode error);
    virtual void onLocalAudioLevel(int volume);
    virtual void onRemoteAudioLevel(int64_t userId, int volume);
    virtual void onKickoff(std::string const &info, floo::BMXErrorCode error);
    virtual void onWarning(std::string const &info, floo::BMXErrorCode error);
    virtual void onError(std::string const &info, floo::BMXErrorCode error);
    virtual void onNetworkQuality(floo::BMXStreamPtr stream, std::string const &info, floo::BMXErrorCode error);
public:
    bool swig_overrides(int n) {
      return (n < 23 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<23> swig_override;
};

class SwigDirector_BMXRTCEngine : public floo::BMXRTCEngine, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXRTCEngine(JNIEnv *jenv);
    virtual ~SwigDirector_BMXRTCEngine();
    virtual void destroy();
    virtual void addRTCEngineListener(floo::BMXRTCEngineListener *listener);
    virtual void removeRTCEngineListener(floo::BMXRTCEngineListener *listener);
    virtual floo::BMXRTCConfigPtr getRTCConfig();
    virtual floo::BMXErrorCode setRoomType(floo::BMXRoomType type);
    virtual floo::BMXErrorCode setStreamRole(floo::BMXStreamRole role);
    virtual floo::BMXErrorCode setVideoCodec(floo::BMXVideoCodec codec);
    virtual floo::BMXErrorCode setVideoProfile(floo::BMXVideoConfigPtr videoConfig);
    virtual floo::BMXErrorCode setAudioProfile(floo::BMXAudioProfile profile);
    virtual floo::BMXErrorCode joinRoom(floo::BMXRoomAuthPtr auth);
    virtual floo::BMXErrorCode leaveRoom();
    virtual floo::BMXErrorCode publish(floo::BMXVideoMediaType type, bool hasVideo, bool hasAudio);
    virtual floo::BMXErrorCode unPublish(floo::BMXVideoMediaType type);
    virtual floo::BMXErrorCode subscribe(floo::BMXStreamPtr stream);
    virtual floo::BMXErrorCode unSubscribe(floo::BMXStreamPtr stream);
    virtual floo::BMXErrorCode startPreview(floo::BMXVideoCanvasPtr canvas);
    virtual floo::BMXErrorCode stopPreview(floo::BMXVideoCanvasPtr canvas);
    virtual floo::BMXErrorCode startRemoteView(floo::BMXVideoCanvasPtr canvas);
    virtual floo::BMXErrorCode stopRemoteView(floo::BMXVideoCanvasPtr canvas);
    virtual floo::BMXErrorCode muteLocalAudio(bool mute);
    virtual floo::BMXErrorCode muteLocalVideo(floo::BMXVideoMediaType type, bool mute);
    virtual floo::BMXErrorCode muteRemoteAudio(floo::BMXStreamPtr stream, bool mute);
    virtual floo::BMXErrorCode muteRemoteVideo(floo::BMXStreamPtr stream, bool mute);
    virtual floo::BMXErrorCode switchCamera();
public:
    bool swig_overrides(int n) {
      return (n < 24 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<24> swig_override;
};

class SwigDirector_BMXRTCSignalServiceListener : public floo::BMXRTCSignalServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXRTCSignalServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXRTCSignalServiceListener();
    virtual void onSessionCreate(floo::BMXRTCSessionPtr session, int error, std::string const reason);
    virtual void onSessionAttach(floo::BMXRTCSessionPtr session, floo::BMXRTCSignalService::HandlerType type, int error, std::string const reason);
    virtual void onRoomCreate(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int error, std::string const &reason);
    virtual void onRoomDestroy(floo::BMXRTCSessionPtr session, int64_t roomId, int error, std::string const &reason);
    virtual void onRoomEdit(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int error, std::string const &reason);
    virtual void onRoomExist(floo::BMXRTCSessionPtr session, int64_t roomId, bool exist, int error, std::string const &reason);
    virtual void onRoomAllowed(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, std::vector< std::string > const &tokens, int error, std::string const &reason);
    virtual void onRoomKick(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int64_t userId, int error, std::string const &reason);
    virtual void onRoomModerate(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int64_t userId, int error, std::string const &reason);
    virtual void onRoomList(floo::BMXRTCSessionPtr session, floo::BMXRTCRooms const &rooms, int error, std::string const &reason);
    virtual void onRoomListParticipants(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRTCRoomParticipants const &participants, int error, std::string const &reason);
    virtual void onPubJoinRoom(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRTCPublishers const &publishers, int error, std::string const &reason);
    virtual void onOtherPubJoinRoom(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRTCPublishers const &publishers);
    virtual void onPubConfigure(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRoomSDPInfoPtr sdp, floo::BMXRTCStreams const streams, int error, std::string const &reason);
    virtual void onPubUnPublish(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int senderId, int error, std::string const &reason);
    virtual void onPublishWebrtcUp(floo::BMXRTCSessionPtr session);
    virtual void onSubJoinRoomUpdate(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRoomSDPInfoPtr sdp, int64_t senderId, floo::BMXRTCStreams const streams, int error, std::string const &reason);
    virtual void onSubStart(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int error, std::string const &reason);
    virtual void onSubPause(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int error, std::string const &reason);
    virtual void onSubUnsubscribe(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, floo::BMXRTCStreams const streams, int error, std::string const &reason);
    virtual void onSubConfigure(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int error, std::string const &reason);
    virtual void onSubSwitch(floo::BMXRTCSessionPtr session, floo::BMXRTCRoomPtr room, int64_t publisher, int error, std::string const &reason);
    virtual void onLeaveRoom(floo::BMXRTCSessionPtr session, int64_t roomId, int64_t senderId, int error, std::string const reason);
    virtual void onSubscribeWebrtcUp(floo::BMXRTCSessionPtr session, int64_t senderId);
    virtual void onMediaInfo(floo::BMXRTCSessionPtr session, int64_t senderId, floo::BMXTrackType type, bool receiving, std::string const &mid);
    virtual void onSlowlink(floo::BMXRTCSessionPtr session, int64_t senderId, bool uplink, int nacks);
    virtual void onHangup(floo::BMXRTCSessionPtr session, int64_t senderId, std::string const &reason);
    virtual void onSessionHangup(floo::BMXRTCSessionPtr session, int64_t error, std::string const &reason);
    virtual void onSessionDetach(floo::BMXRTCSessionPtr session, floo::BMXRTCSignalService::HandlerType type, int error, std::string const reason);
    virtual void onSessionDestroy(int64_t sessionId, int error, std::string const reason);
public:
    bool swig_overrides(int n) {
      return (n < 30 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<30> swig_override;
};

class SwigDirector_BMXRTCServiceListener : public floo::BMXRTCServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXRTCServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXRTCServiceListener();
    virtual void onRTCNoticeStatusChanged(floo::BMXMessagePtr msg, floo::BMXErrorCode error);
    virtual void onRTCNoticeReceive(floo::BMXMessageList const &list);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_BMXRosterServiceListener : public floo::BMXRosterServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXRosterServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXRosterServiceListener();
    virtual void onFriendAdded(int64_t sponsorId, int64_t recipientId);
    virtual void onFriendRemoved(int64_t sponsorId, int64_t recipientId);
    virtual void onApplied(int64_t sponsorId, int64_t recipientId, std::string const &message);
    virtual void onApplicationAccepted(int64_t sponsorId, int64_t recipientId);
    virtual void onApplicationDeclined(int64_t sponsorId, int64_t recipientId, std::string const &reason);
    virtual void onBlockListAdded(int64_t sponsorId, int64_t recipientId);
    virtual void onBlockListRemoved(int64_t sponsorId, int64_t recipientId);
    virtual void onRosterInfoUpdate(floo::BMXRosterItemPtr item);
    virtual void onRosterListUpdate();
public:
    bool swig_overrides(int n) {
      return (n < 9 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<9> swig_override;
};

class SwigDirector_BMXUserServiceListener : public floo::BMXUserServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXUserServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXUserServiceListener();
    virtual void onConnectStatusChanged(floo::BMXConnectStatus status);
    virtual void onUserSignIn(floo::BMXUserProfilePtr profile);
    virtual void onUserSignOut(floo::BMXErrorCode error, int64_t userId);
    virtual void onInfoUpdated(floo::BMXUserProfilePtr profile);
    virtual void onOtherDeviceSingIn(int deviceSN);
    virtual void onOtherDeviceSingOut(int deviceSN);
public:
    bool swig_overrides(int n) {
      return (n < 6 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<6> swig_override;
};

class SwigDirector_BMXGroupServiceListener : public floo::BMXGroupServiceListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_BMXGroupServiceListener(JNIEnv *jenv);
    virtual ~SwigDirector_BMXGroupServiceListener();
    virtual void onGroupCreate(floo::BMXGroupPtr group);
    virtual void onGroupListUpdate(floo::BMXGroupList const &list);
    virtual void onGroupJoined(floo::BMXGroupPtr group);
    virtual void onGroupLeft(floo::BMXGroupPtr group, std::string const &reason);
    virtual void onInvitated(int64_t groupId, int64_t inviter, std::string const &message);
    virtual void onInvitationAccepted(floo::BMXGroupPtr group, int64_t inviteeId);
    virtual void onInvitationDeclined(floo::BMXGroupPtr group, int64_t inviteeId, std::string const &reason);
    virtual void onApplied(floo::BMXGroupPtr group, int64_t applicantId, std::string const &message);
    virtual void onApplicationAccepted(floo::BMXGroupPtr group, int64_t approver);
    virtual void onApplicationDeclined(floo::BMXGroupPtr group, int64_t approver, std::string const &reason);
    virtual void onMembersBanned(floo::BMXGroupPtr group, std::vector< int64_t > const &members, int64_t duration);
    virtual void onMembersUnbanned(floo::BMXGroupPtr group, std::vector< int64_t > const &members);
    virtual void onMemberJoined(floo::BMXGroupPtr group, int64_t memberId, int64_t inviter);
    virtual void onMemberLeft(floo::BMXGroupPtr group, int64_t memberId, std::string const &reason);
    virtual void onAdminsAdded(floo::BMXGroupPtr group, std::vector< int64_t > const &members);
    virtual void onAdminsRemoved(floo::BMXGroupPtr group, std::vector< int64_t > const &members, std::string const &reason);
    virtual void onOwnerAssigned(floo::BMXGroupPtr group);
    virtual void onGroupInfoUpdate(floo::BMXGroupPtr group, floo::BMXGroup::UpdateInfoType type);
    virtual void onMemberChangeNickName(floo::BMXGroupPtr group, int64_t memberId, std::string const &nickName);
    virtual void onAnnouncementUpdate(floo::BMXGroupPtr group, floo::BMXGroup::AnnouncementPtr announcement);
    virtual void onSharedFileUploaded(floo::BMXGroupPtr group, floo::BMXGroup::SharedFilePtr sharedFile);
    virtual void onSharedFileDeleted(floo::BMXGroupPtr group, floo::BMXGroup::SharedFilePtr sharedFile);
    virtual void onSharedFileUpdated(floo::BMXGroupPtr group, floo::BMXGroup::SharedFilePtr sharedFile);
    virtual void onBlockListAdded(floo::BMXGroupPtr group, std::vector< int64_t > const &members);
    virtual void onBlockListRemoved(floo::BMXGroupPtr group, std::vector< int64_t > const &members);
    virtual void onGroupListUpdate();
public:
    bool swig_overrides(int n) {
      return (n < 26 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<26> swig_override;
};


#endif
