/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class ApplicationPage extends BMXBaseObject {
  private transient long swigCPtr;

  protected ApplicationPage(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.ApplicationPage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ApplicationPage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_ApplicationPage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ApplicationPage() {
    this(flooJNI.new_ApplicationPage__SWIG_0(), true);
  }

  public ApplicationPage(BMXRosterServiceApplicationList result, long offset) {
    this(flooJNI.new_ApplicationPage__SWIG_1(BMXRosterServiceApplicationList.getCPtr(result), result, offset), true);
  }

  public ApplicationPage(BMXRosterServiceApplicationList result, String cursor) {
    this(flooJNI.new_ApplicationPage__SWIG_2(BMXRosterServiceApplicationList.getCPtr(result), result, cursor), true);
  }

  public ApplicationPage(ApplicationPage from) {
    this(flooJNI.new_ApplicationPage__SWIG_3(ApplicationPage.getCPtr(from), from), true);
  }

  public long count() {
    return flooJNI.ApplicationPage_count(swigCPtr, this);
  }

  public long offset() {
    return flooJNI.ApplicationPage_offset(swigCPtr, this);
  }

  public String cursor() {
    return flooJNI.ApplicationPage_cursor(swigCPtr, this);
  }

  public BMXRosterServiceApplicationList result() {
    return new BMXRosterServiceApplicationList(flooJNI.ApplicationPage_result(swigCPtr, this), false);
  }

}
