/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

import java.lang.reflect.Field;

public class BMXBaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXBaseObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXBaseObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXBaseObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXBaseObject() {
    this(flooJNI.new_BMXBaseObject(), true);
  }

  @Override
  public boolean equals(Object o) {
    long lSwigCPtrOfO = -1L;
    long lSwigCPtrOfThis = -1L;
    try {
      Class c = o.getClass();
      Field fCPtrOfO = c.getDeclaredField("swigCPtr");
      lSwigCPtrOfO = fCPtrOfO.getLong(o);
      Field fCPtrOfThis = o.getClass().getDeclaredField("swigCPtr");
      lSwigCPtrOfThis = fCPtrOfThis.getLong(this);
    } catch (NoSuchFieldException e) {
      e.printStackTrace();
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
    return o != null && o instanceof BMXBaseObject &&
            (lSwigCPtrOfO == lSwigCPtrOfThis);
  }

  @Override
  public int hashCode() {
    return (int)(this.swigCPtr^(this.swigCPtr>>32));
   }
}
