/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXConversationList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXConversationList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXConversationList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXConversationList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXConversationList() {
    this(flooJNI.new_BMXConversationList__SWIG_0(), true);
  }

  public BMXConversationList(long n) {
    this(flooJNI.new_BMXConversationList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXConversationList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXConversationList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXConversationList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXConversationList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXConversationList_clear(swigCPtr, this);
  }

  public void add(BMXConversation x) {
    flooJNI.BMXConversationList_add(swigCPtr, this, BMXConversation.getCPtr(x), x);
  }

  public BMXConversation get(int i) {
    long cPtr = flooJNI.BMXConversationList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXConversation(cPtr, true);
  }

  public void set(int i, BMXConversation val) {
    flooJNI.BMXConversationList_set(swigCPtr, this, i, BMXConversation.getCPtr(val), val);
  }

}
