/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public enum BMXChannelType {
  Communication,
  Broadcast;

  public final int swigValue() {
    return swigValue;
  }

  public static BMXChannelType swigToEnum(int swigValue) {
    BMXChannelType[] swigValues = BMXChannelType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BMXChannelType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BMXChannelType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BMXChannelType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BMXChannelType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BMXChannelType(BMXChannelType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

