/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

/**
 *  客户端类型
 **/
public enum BMXClientType {
  Unknown(0),
  iOS,
  Android,
  Windows,
  macOS,
  Linux,
  Web;

  public final int swigValue() {
    return swigValue;
  }

  public static BMXClientType swigToEnum(int swigValue) {
    BMXClientType[] swigValues = BMXClientType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BMXClientType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BMXClientType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BMXClientType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BMXClientType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BMXClientType(BMXClientType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

