/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXDeviceList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXDeviceList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXDeviceList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXDeviceList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXDeviceList() {
    this(flooJNI.new_BMXDeviceList__SWIG_0(), true);
  }

  public BMXDeviceList(long n) {
    this(flooJNI.new_BMXDeviceList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXDeviceList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXDeviceList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXDeviceList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXDeviceList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXDeviceList_clear(swigCPtr, this);
  }

  public void add(BMXDevice x) {
    flooJNI.BMXDeviceList_add(swigCPtr, this, BMXDevice.getCPtr(x), x);
  }

  public BMXDevice get(int i) {
    long cPtr = flooJNI.BMXDeviceList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXDevice(cPtr, true);
  }

  public void set(int i, BMXDevice val) {
    flooJNI.BMXDeviceList_set(swigCPtr, this, i, BMXDevice.getCPtr(val), val);
  }

}
