/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupBannedMemberResultPage extends BMXBaseObject {
  public transient long swigCPtr;

  protected BMXGroupBannedMemberResultPage(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXGroupBannedMemberResultPage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupBannedMemberResultPage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupBannedMemberResultPage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BMXGroupBannedMemberResultPage() {
    this(flooJNI.new_BMXGroupBannedMemberResultPage__SWIG_0(), true);
  }

  public BMXGroupBannedMemberResultPage(BMXGroupBannedMemberList result, long offset) {
    this(flooJNI.new_BMXGroupBannedMemberResultPage__SWIG_1(BMXGroupBannedMemberList.getCPtr(result), result, offset), true);
  }

  public BMXGroupBannedMemberResultPage(BMXGroupBannedMemberList result, String cursor) {
    this(flooJNI.new_BMXGroupBannedMemberResultPage__SWIG_2(BMXGroupBannedMemberList.getCPtr(result), result, cursor), true);
  }

  public BMXGroupBannedMemberResultPage(BMXGroupBannedMemberResultPage from) {
    this(flooJNI.new_BMXGroupBannedMemberResultPage__SWIG_3(BMXGroupBannedMemberResultPage.getCPtr(from), from), true);
  }

  public long count() {
    return flooJNI.BMXGroupBannedMemberResultPage_count(swigCPtr, this);
  }

  public long offset() {
    return flooJNI.BMXGroupBannedMemberResultPage_offset(swigCPtr, this);
  }

  public String cursor() {
    return flooJNI.BMXGroupBannedMemberResultPage_cursor(swigCPtr, this);
  }

  public BMXGroupBannedMemberList result() {
    return new BMXGroupBannedMemberList(flooJNI.BMXGroupBannedMemberResultPage_result(swigCPtr, this), false);
  }

}
