/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupBannedMemberList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupBannedMemberList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupBannedMemberList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupBannedMemberList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupBannedMemberList() {
    this(flooJNI.new_BMXGroupBannedMemberList__SWIG_0(), true);
  }

  public BMXGroupBannedMemberList(long n) {
    this(flooJNI.new_BMXGroupBannedMemberList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupBannedMemberList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupBannedMemberList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupBannedMemberList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupBannedMemberList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupBannedMemberList_clear(swigCPtr, this);
  }

  public void add(BMXGroup.BannedMember x) {
    flooJNI.BMXGroupBannedMemberList_add(swigCPtr, this, BMXGroup.BannedMember.getCPtr(x));
  }

  public BMXGroup.BannedMember get(int i) {
    long cPtr = flooJNI.BMXGroupBannedMemberList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup.BannedMember(cPtr, true);
  }

  public void set(int i, BMXGroup.BannedMember val) {
    flooJNI.BMXGroupBannedMemberList_set(swigCPtr, this, i, BMXGroup.BannedMember.getCPtr(val));
  }

}
