/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupMemberList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupMemberList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupMemberList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupMemberList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupMemberList() {
    this(flooJNI.new_BMXGroupMemberList__SWIG_0(), true);
  }

  public BMXGroupMemberList(long n) {
    this(flooJNI.new_BMXGroupMemberList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupMemberList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupMemberList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupMemberList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupMemberList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupMemberList_clear(swigCPtr, this);
  }

  public void add(BMXGroup.Member x) {
    flooJNI.BMXGroupMemberList_add(swigCPtr, this, BMXGroup.Member.getCPtr(x));
  }

  public BMXGroup.Member get(int i) {
    long cPtr = flooJNI.BMXGroupMemberList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup.Member(cPtr, true);
  }

  public void set(int i, BMXGroup.Member val) {
    flooJNI.BMXGroupMemberList_set(swigCPtr, this, i, BMXGroup.Member.getCPtr(val));
  }

}
