/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupList() {
    this(flooJNI.new_BMXGroupList__SWIG_0(), true);
  }

  public BMXGroupList(long n) {
    this(flooJNI.new_BMXGroupList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupList_clear(swigCPtr, this);
  }

  public void add(BMXGroup x) {
    flooJNI.BMXGroupList_add(swigCPtr, this, BMXGroup.getCPtr(x), x);
  }

  public BMXGroup get(int i) {
    long cPtr = flooJNI.BMXGroupList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup(cPtr, true);
  }

  public void set(int i, BMXGroup val) {
    flooJNI.BMXGroupList_set(swigCPtr, this, i, BMXGroup.getCPtr(val), val);
  }

}
