/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupSharedFileList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupSharedFileList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupSharedFileList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupSharedFileList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupSharedFileList() {
    this(flooJNI.new_BMXGroupSharedFileList__SWIG_0(), true);
  }

  public BMXGroupSharedFileList(long n) {
    this(flooJNI.new_BMXGroupSharedFileList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupSharedFileList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupSharedFileList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupSharedFileList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupSharedFileList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupSharedFileList_clear(swigCPtr, this);
  }

  public void add(BMXGroup.SharedFile x) {
    flooJNI.BMXGroupSharedFileList_add(swigCPtr, this, BMXGroup.SharedFile.getCPtr(x));
  }

  public BMXGroup.SharedFile get(int i) {
    long cPtr = flooJNI.BMXGroupSharedFileList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup.SharedFile(cPtr, true);
  }

  public void set(int i, BMXGroup.SharedFile val) {
    flooJNI.BMXGroupSharedFileList_set(swigCPtr, this, i, BMXGroup.SharedFile.getCPtr(val));
  }

}
