/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupInvitationList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupInvitationList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupInvitationList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupInvitationList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupInvitationList() {
    this(flooJNI.new_BMXGroupInvitationList__SWIG_0(), true);
  }

  public BMXGroupInvitationList(long n) {
    this(flooJNI.new_BMXGroupInvitationList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupInvitationList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupInvitationList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupInvitationList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupInvitationList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupInvitationList_clear(swigCPtr, this);
  }

  public void add(BMXGroup.Invitation x) {
    flooJNI.BMXGroupInvitationList_add(swigCPtr, this, BMXGroup.Invitation.getCPtr(x));
  }

  public BMXGroup.Invitation get(int i) {
    long cPtr = flooJNI.BMXGroupInvitationList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup.Invitation(cPtr, true);
  }

  public void set(int i, BMXGroup.Invitation val) {
    flooJNI.BMXGroupInvitationList_set(swigCPtr, this, i, BMXGroup.Invitation.getCPtr(val));
  }

}
