/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupAnnouncementList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXGroupAnnouncementList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupAnnouncementList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupAnnouncementList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXGroupAnnouncementList() {
    this(flooJNI.new_BMXGroupAnnouncementList__SWIG_0(), true);
  }

  public BMXGroupAnnouncementList(long n) {
    this(flooJNI.new_BMXGroupAnnouncementList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXGroupAnnouncementList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXGroupAnnouncementList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXGroupAnnouncementList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXGroupAnnouncementList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXGroupAnnouncementList_clear(swigCPtr, this);
  }

  public void add(BMXGroup.Announcement x) {
    flooJNI.BMXGroupAnnouncementList_add(swigCPtr, this, BMXGroup.Announcement.getCPtr(x));
  }

  public BMXGroup.Announcement get(int i) {
    long cPtr = flooJNI.BMXGroupAnnouncementList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXGroup.Announcement(cPtr, true);
  }

  public void set(int i, BMXGroup.Announcement val) {
    flooJNI.BMXGroupAnnouncementList_set(swigCPtr, this, i, BMXGroup.Announcement.getCPtr(val));
  }

}
