/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXGroupMemberResultPage extends BMXBaseObject {
  public transient long swigCPtr;

  protected BMXGroupMemberResultPage(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXGroupMemberResultPage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXGroupMemberResultPage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXGroupMemberResultPage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BMXGroupMemberResultPage() {
    this(flooJNI.new_BMXGroupMemberResultPage__SWIG_0(), true);
  }

  public BMXGroupMemberResultPage(BMXGroupMemberList result, long offset) {
    this(flooJNI.new_BMXGroupMemberResultPage__SWIG_1(BMXGroupMemberList.getCPtr(result), result, offset), true);
  }

  public BMXGroupMemberResultPage(BMXGroupMemberList result, String cursor) {
    this(flooJNI.new_BMXGroupMemberResultPage__SWIG_2(BMXGroupMemberList.getCPtr(result), result, cursor), true);
  }

  public BMXGroupMemberResultPage(BMXGroupMemberResultPage from) {
    this(flooJNI.new_BMXGroupMemberResultPage__SWIG_3(BMXGroupMemberResultPage.getCPtr(from), from), true);
  }

  public long count() {
    return flooJNI.BMXGroupMemberResultPage_count(swigCPtr, this);
  }

  public long offset() {
    return flooJNI.BMXGroupMemberResultPage_offset(swigCPtr, this);
  }

  public String cursor() {
    return flooJNI.BMXGroupMemberResultPage_cursor(swigCPtr, this);
  }

  public BMXGroupMemberList result() {
    return new BMXGroupMemberList(flooJNI.BMXGroupMemberResultPage_result(swigCPtr, this), false);
  }

}
