/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXJanusPublisher {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXJanusPublisher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXJanusPublisher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXJanusPublisher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXJanusPublisher(long userId) {
    this(flooJNI.new_BMXJanusPublisher(userId), true);
  }

  public void setMUserId(long value) {
    flooJNI.BMXJanusPublisher_mUserId_set(swigCPtr, this, value);
  }

  public long getMUserId() {
    return flooJNI.BMXJanusPublisher_mUserId_get(swigCPtr, this);
  }

  public void setMDisplay(String value) {
    flooJNI.BMXJanusPublisher_mDisplay_set(swigCPtr, this, value);
  }

  public String getMDisplay() {
    return flooJNI.BMXJanusPublisher_mDisplay_get(swigCPtr, this);
  }

  public void setMAudioCodec(String value) {
    flooJNI.BMXJanusPublisher_mAudioCodec_set(swigCPtr, this, value);
  }

  public String getMAudioCodec() {
    return flooJNI.BMXJanusPublisher_mAudioCodec_get(swigCPtr, this);
  }

  public void setMVideoCodec(String value) {
    flooJNI.BMXJanusPublisher_mVideoCodec_set(swigCPtr, this, value);
  }

  public String getMVideoCodec() {
    return flooJNI.BMXJanusPublisher_mVideoCodec_get(swigCPtr, this);
  }

  public void setMSimulcast(boolean value) {
    flooJNI.BMXJanusPublisher_mSimulcast_set(swigCPtr, this, value);
  }

  public boolean getMSimulcast() {
    return flooJNI.BMXJanusPublisher_mSimulcast_get(swigCPtr, this);
  }

  public void setMTalking(boolean value) {
    flooJNI.BMXJanusPublisher_mTalking_set(swigCPtr, this, value);
  }

  public boolean getMTalking() {
    return flooJNI.BMXJanusPublisher_mTalking_get(swigCPtr, this);
  }

  public void setStreams(BMXRTCStreams value) {
    flooJNI.BMXJanusPublisher_streams_set(swigCPtr, this, BMXRTCStreams.getCPtr(value), value);
  }

  public BMXRTCStreams getStreams() {
    long cPtr = flooJNI.BMXJanusPublisher_streams_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BMXRTCStreams(cPtr, false);
  }

}
