/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXMessageListList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXMessageListList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXMessageListList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXMessageListList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXMessageListList() {
    this(flooJNI.new_BMXMessageListList__SWIG_0(), true);
  }

  public BMXMessageListList(long n) {
    this(flooJNI.new_BMXMessageListList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXMessageListList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXMessageListList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXMessageListList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXMessageListList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXMessageListList_clear(swigCPtr, this);
  }

  public void add(BMXMessageList x) {
    flooJNI.BMXMessageListList_add(swigCPtr, this, BMXMessageList.getCPtr(x), x);
  }

  public BMXMessageList get(int i) {
    return new BMXMessageList(flooJNI.BMXMessageListList_get(swigCPtr, this, i), false);
  }

  public void set(int i, BMXMessageList val) {
    flooJNI.BMXMessageListList_set(swigCPtr, this, i, BMXMessageList.getCPtr(val), val);
  }

}
