/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXPushUserProfile extends BMXBaseObject {
  public transient long swigCPtr;

  protected BMXPushUserProfile(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXPushUserProfile_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public BMXPushUserProfile() {
    super(flooJNI.BMXPushUserProfile_SWIGUpcast(0), true);
    swigCPtr = 0;
  }

  protected static long getCPtr(BMXPushUserProfile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXPushUserProfile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  static public class MessagePushSetting {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected MessagePushSetting(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(MessagePushSetting obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          flooJNI.delete_BMXPushUserProfile_MessagePushSetting(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public MessagePushSetting() {
      this(flooJNI.new_BMXPushUserProfile_MessagePushSetting(), true);
    }
  
    public void setMPushEnabled(boolean value) {
      flooJNI.BMXPushUserProfile_MessagePushSetting_mPushEnabled_set(swigCPtr, this, value);
    }
  
    public boolean getMPushEnabled() {
      return flooJNI.BMXPushUserProfile_MessagePushSetting_mPushEnabled_get(swigCPtr, this);
    }
  
    public void setMSilenceStartTime(int value) {
      flooJNI.BMXPushUserProfile_MessagePushSetting_mSilenceStartTime_set(swigCPtr, this, value);
    }
  
    public int getMSilenceStartTime() {
      return flooJNI.BMXPushUserProfile_MessagePushSetting_mSilenceStartTime_get(swigCPtr, this);
    }
  
    public void setMSilenceEndTime(int value) {
      flooJNI.BMXPushUserProfile_MessagePushSetting_mSilenceEndTime_set(swigCPtr, this, value);
    }
  
    public int getMSilenceEndTime() {
      return flooJNI.BMXPushUserProfile_MessagePushSetting_mSilenceEndTime_get(swigCPtr, this);
    }
  
    public void setMPushStartTime(int value) {
      flooJNI.BMXPushUserProfile_MessagePushSetting_mPushStartTime_set(swigCPtr, this, value);
    }
  
    public int getMPushStartTime() {
      return flooJNI.BMXPushUserProfile_MessagePushSetting_mPushStartTime_get(swigCPtr, this);
    }
  
    public void setMPushEndTime(int value) {
      flooJNI.BMXPushUserProfile_MessagePushSetting_mPushEndTime_set(swigCPtr, this, value);
    }
  
    public int getMPushEndTime() {
      return flooJNI.BMXPushUserProfile_MessagePushSetting_mPushEndTime_get(swigCPtr, this);
    }
  
  }

  public long userId() {
    return flooJNI.BMXPushUserProfile_userId(swigCPtr, this);
  }

  public String pushAlias() {
    return flooJNI.BMXPushUserProfile_pushAlias(swigCPtr, this);
  }

  public String pushToken() {
    return flooJNI.BMXPushUserProfile_pushToken(swigCPtr, this);
  }

  public BMXPushUserProfile.MessagePushSetting messagePushSetting() {
    return new BMXPushUserProfile.MessagePushSetting(flooJNI.BMXPushUserProfile_messagePushSetting(swigCPtr, this), false);
  }

}
