/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCServiceListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRTCServiceListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCServiceListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCServiceListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    flooJNI.BMXRTCServiceListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    flooJNI.BMXRTCServiceListener_change_ownership(this, swigCPtr, true);
  }

  public BMXRTCServiceListener() {
    this(flooJNI.new_BMXRTCServiceListener(), true);
    flooJNI.BMXRTCServiceListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void onRTCNoticeStatusChanged(BMXMessage msg, BMXErrorCode error) {
    if (getClass() == BMXRTCServiceListener.class) flooJNI.BMXRTCServiceListener_onRTCNoticeStatusChanged(swigCPtr, this, BMXMessage.getCPtr(msg), msg, error.swigValue()); else flooJNI.BMXRTCServiceListener_onRTCNoticeStatusChangedSwigExplicitBMXRTCServiceListener(swigCPtr, this, BMXMessage.getCPtr(msg), msg, error.swigValue());
  }

  public void onRTCNoticeReceive(BMXMessageList list) {
    if (getClass() == BMXRTCServiceListener.class) flooJNI.BMXRTCServiceListener_onRTCNoticeReceive(swigCPtr, this, BMXMessageList.getCPtr(list), list); else flooJNI.BMXRTCServiceListener_onRTCNoticeReceiveSwigExplicitBMXRTCServiceListener(swigCPtr, this, BMXMessageList.getCPtr(list), list);
  }

  public void registerRTCService(BMXRTCService service) {
    flooJNI.BMXRTCServiceListener_registerRTCService(swigCPtr, this, BMXRTCService.getCPtr(service), service);
  }

}
