/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCRoomParticipants {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRTCRoomParticipants(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCRoomParticipants obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCRoomParticipants(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRTCRoomParticipants() {
    this(flooJNI.new_BMXRTCRoomParticipants__SWIG_0(), true);
  }

  public BMXRTCRoomParticipants(long n) {
    this(flooJNI.new_BMXRTCRoomParticipants__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXRTCRoomParticipants_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXRTCRoomParticipants_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXRTCRoomParticipants_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXRTCRoomParticipants_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXRTCRoomParticipants_clear(swigCPtr, this);
  }

  public void add(BMXRoomParticipant x) {
    flooJNI.BMXRTCRoomParticipants_add(swigCPtr, this, BMXRoomParticipant.getCPtr(x), x);
  }

  public BMXRoomParticipant get(int i) {
    long cPtr = flooJNI.BMXRTCRoomParticipants_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXRoomParticipant(cPtr, true);
  }

  public void set(int i, BMXRoomParticipant val) {
    flooJNI.BMXRTCRoomParticipants_set(swigCPtr, this, i, BMXRoomParticipant.getCPtr(val), val);
  }

}
