/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCConfig {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXRTCConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRTCConfig() {
    this(flooJNI.new_BMXRTCConfig(), true);
  }

  public String getVersion() {
    return flooJNI.BMXRTCConfig_getVersion(swigCPtr, this);
  }

  public void setLogLevel(BMXLogLevel level) {
    flooJNI.BMXRTCConfig_setLogLevel(swigCPtr, this, level.swigValue());
  }

  public BMXLogLevel getLogLevel() {
    return BMXLogLevel.swigToEnum(flooJNI.BMXRTCConfig_getLogLevel(swigCPtr, this));
  }

  public void setSDKMode(BMXSDKMode mode) {
    flooJNI.BMXRTCConfig_setSDKMode(swigCPtr, this, mode.swigValue());
  }

  public BMXSDKMode getSDKMode() {
    return BMXSDKMode.swigToEnum(flooJNI.BMXRTCConfig_getSDKMode(swigCPtr, this));
  }

  public void setAutoPublishMode(boolean autoPublish) {
    flooJNI.BMXRTCConfig_setAutoPublishMode(swigCPtr, this, autoPublish);
  }

  public boolean getAutoPublishMode() {
    return flooJNI.BMXRTCConfig_getAutoPublishMode(swigCPtr, this);
  }

  public void setAutoSubscribeMode(boolean autoSubscribe) {
    flooJNI.BMXRTCConfig_setAutoSubscribeMode(swigCPtr, this, autoSubscribe);
  }

  public boolean getAutoSubscribeMode() {
    return flooJNI.BMXRTCConfig_getAutoSubscribeMode(swigCPtr, this);
  }

  public void setAudioOnlyMode(boolean audioOnly) {
    flooJNI.BMXRTCConfig_setAudioOnlyMode(swigCPtr, this, audioOnly);
  }

  public boolean getAudioOnlyMode() {
    return flooJNI.BMXRTCConfig_getAudioOnlyMode(swigCPtr, this);
  }

  public void setEnableLocalAudio(boolean enableLocalAudio) {
    flooJNI.BMXRTCConfig_setEnableLocalAudio(swigCPtr, this, enableLocalAudio);
  }

  public boolean getEnableLocalAudio() {
    return flooJNI.BMXRTCConfig_getEnableLocalAudio(swigCPtr, this);
  }

  public void setEnableLocalVideo(boolean enableLocalVideo) {
    flooJNI.BMXRTCConfig_setEnableLocalVideo(swigCPtr, this, enableLocalVideo);
  }

  public boolean getEnableLocalVideo() {
    return flooJNI.BMXRTCConfig_getEnableLocalVideo(swigCPtr, this);
  }

}
