/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCRooms {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRTCRooms(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCRooms obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCRooms(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRTCRooms() {
    this(flooJNI.new_BMXRTCRooms__SWIG_0(), true);
  }

  public BMXRTCRooms(long n) {
    this(flooJNI.new_BMXRTCRooms__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXRTCRooms_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXRTCRooms_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXRTCRooms_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXRTCRooms_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXRTCRooms_clear(swigCPtr, this);
  }

  public void add(BMXRTCRoom x) {
    flooJNI.BMXRTCRooms_add(swigCPtr, this, BMXRTCRoom.getCPtr(x), x);
  }

  public BMXRTCRoom get(int i) {
    long cPtr = flooJNI.BMXRTCRooms_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXRTCRoom(cPtr, true);
  }

  public void set(int i, BMXRTCRoom val) {
    flooJNI.BMXRTCRooms_set(swigCPtr, this, i, BMXRTCRoom.getCPtr(val), val);
  }

}
