/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRoomSDPInfo {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXRoomSDPInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRoomSDPInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRoomSDPInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRoomSDPInfo() {
    this(flooJNI.new_BMXRoomSDPInfo(), true);
  }

  public void setSdp(String value) {
    flooJNI.BMXRoomSDPInfo_sdp_set(swigCPtr, this, value);
  }

  public String getSdp() {
    return flooJNI.BMXRoomSDPInfo_sdp_get(swigCPtr, this);
  }

  public void setType(BMXRoomSDPType value) {
    flooJNI.BMXRoomSDPInfo_type_set(swigCPtr, this, value.swigValue());
  }

  public BMXRoomSDPType getType() {
    return BMXRoomSDPType.swigToEnum(flooJNI.BMXRoomSDPInfo_type_get(swigCPtr, this));
  }

}
