/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public enum BMXRenderMode {
  Default,
  Fit,
  Fill;

  public final int swigValue() {
    return swigValue;
  }

  public static BMXRenderMode swigToEnum(int swigValue) {
    BMXRenderMode[] swigValues = BMXRenderMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BMXRenderMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BMXRenderMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BMXRenderMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BMXRenderMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BMXRenderMode(BMXRenderMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

