/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCPublishers {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRTCPublishers(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCPublishers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCPublishers(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRTCPublishers() {
    this(flooJNI.new_BMXRTCPublishers__SWIG_0(), true);
  }

  public BMXRTCPublishers(long n) {
    this(flooJNI.new_BMXRTCPublishers__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXRTCPublishers_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXRTCPublishers_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXRTCPublishers_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXRTCPublishers_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXRTCPublishers_clear(swigCPtr, this);
  }

  public void add(BMXJanusPublisher x) {
    flooJNI.BMXRTCPublishers_add(swigCPtr, this, BMXJanusPublisher.getCPtr(x), x);
  }

  public BMXJanusPublisher get(int i) {
    long cPtr = flooJNI.BMXRTCPublishers_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXJanusPublisher(cPtr, true);
  }

  public void set(int i, BMXJanusPublisher val) {
    flooJNI.BMXRTCPublishers_set(swigCPtr, this, i, BMXJanusPublisher.getCPtr(val), val);
  }

}
