/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRosterItemList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRosterItemList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRosterItemList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRosterItemList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRosterItemList() {
    this(flooJNI.new_BMXRosterItemList__SWIG_0(), true);
  }

  public BMXRosterItemList(long n) {
    this(flooJNI.new_BMXRosterItemList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXRosterItemList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXRosterItemList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXRosterItemList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXRosterItemList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXRosterItemList_clear(swigCPtr, this);
  }

  public void add(BMXRosterItem x) {
    flooJNI.BMXRosterItemList_add(swigCPtr, this, BMXRosterItem.getCPtr(x), x);
  }

  public BMXRosterItem get(int i) {
    long cPtr = flooJNI.BMXRosterItemList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXRosterItem(cPtr, true);
  }

  public void set(int i, BMXRosterItem val) {
    flooJNI.BMXRosterItemList_set(swigCPtr, this, i, BMXRosterItem.getCPtr(val), val);
  }

}
