/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCStreams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BMXRTCStreams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCStreams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRTCStreams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRTCStreams() {
    this(flooJNI.new_BMXRTCStreams__SWIG_0(), true);
  }

  public BMXRTCStreams(long n) {
    this(flooJNI.new_BMXRTCStreams__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.BMXRTCStreams_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.BMXRTCStreams_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.BMXRTCStreams_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.BMXRTCStreams_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.BMXRTCStreams_clear(swigCPtr, this);
  }

  public void add(BMXJanusStreamInfo x) {
    flooJNI.BMXRTCStreams_add(swigCPtr, this, BMXJanusStreamInfo.getCPtr(x), x);
  }

  public BMXJanusStreamInfo get(int i) {
    long cPtr = flooJNI.BMXRTCStreams_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BMXJanusStreamInfo(cPtr, true);
  }

  public void set(int i, BMXJanusStreamInfo val) {
    flooJNI.BMXRTCStreams_set(swigCPtr, this, i, BMXJanusStreamInfo.getCPtr(val), val);
  }

}
