/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRTCRoom extends BMXBaseObject {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BMXRTCRoom(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXRTCRoom_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRTCRoom obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        flooJNI.delete_BMXRTCRoom(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long roomId() {
    return flooJNI.BMXRTCRoom_roomId(swigCPtr, this);
  }

  public void setRoomSecret(String roomSecret) {
    flooJNI.BMXRTCRoom_setRoomSecret(swigCPtr, this, roomSecret);
  }

  public String roomSecret() {
    return flooJNI.BMXRTCRoom_roomSecret(swigCPtr, this);
  }

  public void setPin(String pin) {
    flooJNI.BMXRTCRoom_setPin(swigCPtr, this, pin);
  }

  public String pin() {
    return flooJNI.BMXRTCRoom_pin(swigCPtr, this);
  }

  public boolean permanent() {
    return flooJNI.BMXRTCRoom_permanent(swigCPtr, this);
  }

  public boolean isPrivate() {
    return flooJNI.BMXRTCRoom_isPrivate(swigCPtr, this);
  }

  public String roomDescription() {
    return flooJNI.BMXRTCRoom_roomDescription(swigCPtr, this);
  }

  public long roomPrivateId() {
    return flooJNI.BMXRTCRoom_roomPrivateId(swigCPtr, this);
  }

}
