/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRoomAuth {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXRoomAuth(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRoomAuth obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRoomAuth(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMRoomId(long value) {
    flooJNI.BMXRoomAuth_mRoomId_set(swigCPtr, this, value);
  }

  public long getMRoomId() {
    return flooJNI.BMXRoomAuth_mRoomId_get(swigCPtr, this);
  }

  public void setMToken(String value) {
    flooJNI.BMXRoomAuth_mToken_set(swigCPtr, this, value);
  }

  public String getMToken() {
    return flooJNI.BMXRoomAuth_mToken_get(swigCPtr, this);
  }

  public void setMOptionalInfo(String value) {
    flooJNI.BMXRoomAuth_mOptionalInfo_set(swigCPtr, this, value);
  }

  public String getMOptionalInfo() {
    return flooJNI.BMXRoomAuth_mOptionalInfo_get(swigCPtr, this);
  }

  public void setMUserId(long value) {
    flooJNI.BMXRoomAuth_mUserId_set(swigCPtr, this, value);
  }

  public long getMUserId() {
    return flooJNI.BMXRoomAuth_mUserId_get(swigCPtr, this);
  }

  public BMXRoomAuth() {
    this(flooJNI.new_BMXRoomAuth(), true);
  }

}
