/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXRoomParticipant {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXRoomParticipant(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXRoomParticipant obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXRoomParticipant(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BMXRoomParticipant() {
    this(flooJNI.new_BMXRoomParticipant(), true);
  }

  public void setMUserId(long value) {
    flooJNI.BMXRoomParticipant_mUserId_set(swigCPtr, this, value);
  }

  public long getMUserId() {
    return flooJNI.BMXRoomParticipant_mUserId_get(swigCPtr, this);
  }

  public void setMDisplay(String value) {
    flooJNI.BMXRoomParticipant_mDisplay_set(swigCPtr, this, value);
  }

  public String getMDisplay() {
    return flooJNI.BMXRoomParticipant_mDisplay_get(swigCPtr, this);
  }

  public void setMIsPublisher(boolean value) {
    flooJNI.BMXRoomParticipant_mIsPublisher_set(swigCPtr, this, value);
  }

  public boolean getMIsPublisher() {
    return flooJNI.BMXRoomParticipant_mIsPublisher_get(swigCPtr, this);
  }

  public void setMIstalking(boolean value) {
    flooJNI.BMXRoomParticipant_mIstalking_set(swigCPtr, this, value);
  }

  public boolean getMIstalking() {
    return flooJNI.BMXRoomParticipant_mIstalking_get(swigCPtr, this);
  }

}
