/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXStream {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMUserId(long value) {
    flooJNI.BMXStream_mUserId_set(swigCPtr, this, value);
  }

  public long getMUserId() {
    return flooJNI.BMXStream_mUserId_get(swigCPtr, this);
  }

  public void setMStreamId(String value) {
    flooJNI.BMXStream_mStreamId_set(swigCPtr, this, value);
  }

  public String getMStreamId() {
    return flooJNI.BMXStream_mStreamId_get(swigCPtr, this);
  }

  public void setMMediaType(BMXVideoMediaType value) {
    flooJNI.BMXStream_mMediaType_set(swigCPtr, this, value.swigValue());
  }

  public BMXVideoMediaType getMMediaType() {
    return BMXVideoMediaType.swigToEnum(flooJNI.BMXStream_mMediaType_get(swigCPtr, this));
  }

  public void setMEnableVideo(boolean value) {
    flooJNI.BMXStream_mEnableVideo_set(swigCPtr, this, value);
  }

  public boolean getMEnableVideo() {
    return flooJNI.BMXStream_mEnableVideo_get(swigCPtr, this);
  }

  public void setMEnableAudio(boolean value) {
    flooJNI.BMXStream_mEnableAudio_set(swigCPtr, this, value);
  }

  public boolean getMEnableAudio() {
    return flooJNI.BMXStream_mEnableAudio_get(swigCPtr, this);
  }

  public void setMEnableData(boolean value) {
    flooJNI.BMXStream_mEnableData_set(swigCPtr, this, value);
  }

  public boolean getMEnableData() {
    return flooJNI.BMXStream_mEnableData_get(swigCPtr, this);
  }

  public void setMMuteVideo(boolean value) {
    flooJNI.BMXStream_mMuteVideo_set(swigCPtr, this, value);
  }

  public boolean getMMuteVideo() {
    return flooJNI.BMXStream_mMuteVideo_get(swigCPtr, this);
  }

  public void setMMuteAudio(boolean value) {
    flooJNI.BMXStream_mMuteAudio_set(swigCPtr, this, value);
  }

  public boolean getMMuteAudio() {
    return flooJNI.BMXStream_mMuteAudio_get(swigCPtr, this);
  }

  public BMXStream() {
    this(flooJNI.new_BMXStream(), true);
  }

}
