/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

/**
 *  登录状态
 **/
public enum BMXSignInStatus {
  SignOut,
  SignIn;

  public final int swigValue() {
    return swigValue;
  }

  public static BMXSignInStatus swigToEnum(int swigValue) {
    BMXSignInStatus[] swigValues = BMXSignInStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BMXSignInStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BMXSignInStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BMXSignInStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BMXSignInStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BMXSignInStatus(BMXSignInStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

