/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

/**
 *  音频消息附件
 **/
public class BMXVoiceAttachment extends BMXFileAttachment {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BMXVoiceAttachment(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXVoiceAttachment_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXVoiceAttachment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        flooJNI.delete_BMXVoiceAttachment(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  构造函数，构建发送音频消息附件
   * @param path 文件的本地路径
   * @param duration 音频时长
   * @param displayName 文件展示名
   **/
  public BMXVoiceAttachment(String path, int duration, String displayName) {
    this(flooJNI.new_BMXVoiceAttachment__SWIG_0(path, duration, displayName), true);
  }

  public BMXVoiceAttachment(String path, int duration) {
    this(flooJNI.new_BMXVoiceAttachment__SWIG_1(path, duration), true);
  }

  /**
   *  构造函数，构建接收音频消息附件
   * @param url 文件服务器地址
   * @param duration 音频时长
   * @param displayName 文件展示名
   * @param fileLength 文件大小
   **/
  public BMXVoiceAttachment(String url, int duration, String displayName, long fileLength) {
    this(flooJNI.new_BMXVoiceAttachment__SWIG_2(url, duration, displayName, fileLength), true);
  }

  /**
   *  返回文件类型
   * @return Type
   **/
  public BMXMessageAttachment.Type type() {
    return BMXMessageAttachment.Type.swigToEnum(flooJNI.BMXVoiceAttachment_type(swigCPtr, this));
  }

  /**
   *  克隆函数
   * @return BMXMessageAttachmentPtr
   **/
  public BMXMessageAttachment clone() {
    long cPtr = flooJNI.BMXVoiceAttachment_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BMXMessageAttachment(cPtr, true);
  }

  /**
   *  语音时长
   * @return int32_t
   **/
  public int duration() {
    return flooJNI.BMXVoiceAttachment_duration(swigCPtr, this);
  }

  public static BMXVoiceAttachment dynamic_cast(BMXMessageAttachment attachment) {
    long cPtr = flooJNI.BMXVoiceAttachment_dynamic_cast(BMXMessageAttachment.getCPtr(attachment), attachment);
    return (cPtr == 0) ? null : new BMXVoiceAttachment(cPtr, true);
  }

}
