/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

/**
 *  视频消息附件
 **/
public class BMXVideoAttachment extends BMXFileAttachment {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BMXVideoAttachment(long cPtr, boolean cMemoryOwn) {
    super(flooJNI.BMXVideoAttachment_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXVideoAttachment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        flooJNI.delete_BMXVideoAttachment(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  构造函数，构建发送视频消息附件
   * @param path 文件的本地路径
   * @param duration 视频片段时长
   * @param size 视频大小，宽度和高度
   * @param displayName 文件展示名
   **/
  public BMXVideoAttachment(String path, int duration, BMXMessageAttachment.Size size, String displayName) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_0(path, duration, BMXMessageAttachment.Size.getCPtr(size), size, displayName), true);
  }

  public BMXVideoAttachment(String path, int duration, BMXMessageAttachment.Size size) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_1(path, duration, BMXMessageAttachment.Size.getCPtr(size), size), true);
  }

  /**
   *  构造函数，构建发送视频消息附件
   * @param path 文件的本地路径
   * @param thumbnailPath 缩略图文件的本地路径
   * @param duration 视频片段时长
   * @param size 视频大小，宽度和高度
   * @param displayName 文件展示名
   **/
  public BMXVideoAttachment(String path, String thumbnailPath, int duration, BMXMessageAttachment.Size size, String displayName) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_2(path, thumbnailPath, duration, BMXMessageAttachment.Size.getCPtr(size), size, displayName), true);
  }

  public BMXVideoAttachment(String path, String thumbnailPath, int duration, BMXMessageAttachment.Size size) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_3(path, thumbnailPath, duration, BMXMessageAttachment.Size.getCPtr(size), size), true);
  }

  /**
   *  构造函数，构建接收视频消息附件
   * @param ratelUrl ratel服务器地址
   * @param duration 视频片段时长
   * @param size 视频大小，宽度和高度
   * @param displayName 文件展示名
   * @param fileLength 文件大小
   **/
  public BMXVideoAttachment(String ratelUrl, int duration, BMXMessageAttachment.Size size, String displayName, long fileLength) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_4(ratelUrl, duration, BMXMessageAttachment.Size.getCPtr(size), size, displayName, fileLength), true);
  }

  /**
   *  构造函数，构建接收视频消息附件
   * @param ratelUrl ratel服务器地址
   * @param thumbnailUrl 缩略图文件服务器地址
   * @param duration 视频片段时长
   * @param size 视频大小，宽度和高度
   * @param displayName 文件展示名
   * @param fileLength 文件大小
   **/
  public BMXVideoAttachment(String ratelUrl, String thumbnailUrl, int duration, BMXMessageAttachment.Size size, String displayName, long fileLength) {
    this(flooJNI.new_BMXVideoAttachment__SWIG_5(ratelUrl, thumbnailUrl, duration, BMXMessageAttachment.Size.getCPtr(size), size, displayName, fileLength), true);
  }

  /**
   *  返回文件类型
   * @return Type
   **/
  public BMXMessageAttachment.Type type() {
    return BMXMessageAttachment.Type.swigToEnum(flooJNI.BMXVideoAttachment_type(swigCPtr, this));
  }

  /**
   *  克隆函数
   * @return BMXMessageAttachmentPtr
   **/
  public BMXMessageAttachment clone() {
    long cPtr = flooJNI.BMXVideoAttachment_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BMXMessageAttachment(cPtr, true);
  }

  /**
   *  视频大小，宽度和高度
   * @return Size
   **/
  public BMXMessageAttachment.Size size() {
    return new BMXMessageAttachment.Size(flooJNI.BMXVideoAttachment_size(swigCPtr, this), false);
  }

  /**
   *  视频片段时长
   * @return int32_t
   **/
  public int duration() {
    return flooJNI.BMXVideoAttachment_duration(swigCPtr, this);
  }

  /**
   *  设置发送视频片段消息缩略图
   * @param path 视频片段消息缩略图
   **/
  public void setThumbnail(String path) {
    flooJNI.BMXVideoAttachment_setThumbnail(swigCPtr, this, path);
  }

  /**
   *  缩略图本地路径
   * @return std::string
   **/
  public String thumbnailPath() {
    return flooJNI.BMXVideoAttachment_thumbnailPath(swigCPtr, this);
  }

  /**
   *  缩略图服务器路径
   * @return std::string
   **/
  public String thumbnailUrl() {
    return flooJNI.BMXVideoAttachment_thumbnailUrl(swigCPtr, this);
  }

  public void setThumbnailRatelUrl(String thumbnailRatelUrl) {
    flooJNI.BMXVideoAttachment_setThumbnailRatelUrl(swigCPtr, this, thumbnailRatelUrl);
  }

  public String thumbnailRatelUrl() {
    return flooJNI.BMXVideoAttachment_thumbnailRatelUrl(swigCPtr, this);
  }

  /**
   *  缩略图下载状态
   * @return DownloadStatus
   **/
  public BMXMessageAttachment.DownloadStatus thumbnailDownloadStatus() {
    return BMXMessageAttachment.DownloadStatus.swigToEnum(flooJNI.BMXVideoAttachment_thumbnailDownloadStatus(swigCPtr, this));
  }

  public static BMXVideoAttachment dynamic_cast(BMXMessageAttachment attachment) {
    long cPtr = flooJNI.BMXVideoAttachment_dynamic_cast(BMXMessageAttachment.getCPtr(attachment), attachment);
    return (cPtr == 0) ? null : new BMXVideoAttachment(cPtr, true);
  }

}
