/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

import android.view.View;

public class BMXVideoCanvas {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;
  private View mView;
  protected BMXVideoCanvas(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXVideoCanvas obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXVideoCanvas(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMView(View value) {
    mView = value;
  }

  public View getMView() {
    return mView;
  }

  public void setMUserId(long value) {
    flooJNI.BMXVideoCanvas_mUserId_set(swigCPtr, this, value);
  }

  public long getMUserId() {
    return flooJNI.BMXVideoCanvas_mUserId_get(swigCPtr, this);
  }

  public void setMStream(BMXStream value) {
    flooJNI.BMXVideoCanvas_mStream_set(swigCPtr, this, BMXStream.getCPtr(value), value);
  }

  public BMXStream getMStream() {
    long cPtr = flooJNI.BMXVideoCanvas_mStream_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BMXStream(cPtr, true);
  }

  public void setMRenderMode(BMXRenderMode value) {
    flooJNI.BMXVideoCanvas_mRenderMode_set(swigCPtr, this, value.swigValue());
  }

  public BMXRenderMode getMRenderMode() {
    return BMXRenderMode.swigToEnum(flooJNI.BMXVideoCanvas_mRenderMode_get(swigCPtr, this));
  }

  public void setMMirrodMode(BMXMirrorMode value) {
    flooJNI.BMXVideoCanvas_mMirrodMode_set(swigCPtr, this, value.swigValue());
  }

  public BMXMirrorMode getMMirrodMode() {
    return BMXMirrorMode.swigToEnum(flooJNI.BMXVideoCanvas_mMirrodMode_get(swigCPtr, this));
  }

  public BMXVideoCanvas() {
    this(flooJNI.new_BMXVideoCanvas(), true);
  }

}
