/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public enum BMXVideoProfile {
  None,
  Profile_240_180,
  Profile_320_180,
  Profile_320_240,
  Profile_480_360,
  Profile_640_360,
  Profile_640_480,
  Profile_960_720,
  Profile_1280_720,
  Profile_1920_1080;

  public final int swigValue() {
    return swigValue;
  }

  public static BMXVideoProfile swigToEnum(int swigValue) {
    BMXVideoProfile[] swigValues = BMXVideoProfile.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BMXVideoProfile swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BMXVideoProfile.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BMXVideoProfile() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BMXVideoProfile(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BMXVideoProfile(BMXVideoProfile swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

