/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class BMXVideoConfig {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BMXVideoConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BMXVideoConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_BMXVideoConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(int value) {
    flooJNI.BMXVideoConfig_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return flooJNI.BMXVideoConfig_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    flooJNI.BMXVideoConfig_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return flooJNI.BMXVideoConfig_height_get(swigCPtr, this);
  }

  public void setFrameRate(int value) {
    flooJNI.BMXVideoConfig_frameRate_set(swigCPtr, this, value);
  }

  public int getFrameRate() {
    return flooJNI.BMXVideoConfig_frameRate_get(swigCPtr, this);
  }

  public void setProfile(BMXVideoProfile value) {
    flooJNI.BMXVideoConfig_profile_set(swigCPtr, this, value.swigValue());
  }

  public BMXVideoProfile getProfile() {
    return BMXVideoProfile.swigToEnum(flooJNI.BMXVideoConfig_profile_get(swigCPtr, this));
  }

  public BMXVideoConfig() {
    this(flooJNI.new_BMXVideoConfig(), true);
  }

}
