/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class floo implements flooConstants {
  public static String getErrorMessage(BMXErrorCode errorCode) {
    return flooJNI.getErrorMessage(errorCode.swigValue());
  }

  public static String getKMentionAll() {
    return flooJNI.kMentionAll_get();
  }

  public static String getKMentionList() {
    return flooJNI.kMentionList_get();
  }

  public static String getKMentionedMessage() {
    return flooJNI.kMentionedMessage_get();
  }

  public static String getKPushMessage() {
    return flooJNI.kPushMessage_get();
  }

  public static String getKSenderNickname() {
    return flooJNI.kSenderNickname_get();
  }

  public static String getKGroupAck() {
    return flooJNI.kGroupAck_get();
  }

  public static String getKGroupMemberList() {
    return flooJNI.kGroupMemberList_get();
  }

  public static String encodeBMXMessageConfig(BMXMessageConfig arg0) {
    return flooJNI.encodeBMXMessageConfig(BMXMessageConfig.getCPtr(arg0), arg0);
  }

  public static BMXMessageConfig decodeBMXMessageConfig(String config) {
    long cPtr = flooJNI.decodeBMXMessageConfig(config);
    return (cPtr == 0) ? null : new BMXMessageConfig(cPtr, true);
  }

}
