/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class ListOfLongLong {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ListOfLongLong(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListOfLongLong obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_ListOfLongLong(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListOfLongLong() {
    this(flooJNI.new_ListOfLongLong__SWIG_0(), true);
  }

  public ListOfLongLong(long n) {
    this(flooJNI.new_ListOfLongLong__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.ListOfLongLong_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.ListOfLongLong_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.ListOfLongLong_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.ListOfLongLong_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.ListOfLongLong_clear(swigCPtr, this);
  }

  public void add(long x) {
    flooJNI.ListOfLongLong_add(swigCPtr, this, x);
  }

  public long get(int i) {
    return flooJNI.ListOfLongLong_get(swigCPtr, this, i);
  }

  public void set(int i, long val) {
    flooJNI.ListOfLongLong_set(swigCPtr, this, i, val);
  }

}
