/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.floo.floolib;

public class TagList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TagList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        flooJNI.delete_TagList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TagList() {
    this(flooJNI.new_TagList__SWIG_0(), true);
  }

  public TagList(long n) {
    this(flooJNI.new_TagList__SWIG_1(n), true);
  }

  public long size() {
    return flooJNI.TagList_size(swigCPtr, this);
  }

  public long capacity() {
    return flooJNI.TagList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    flooJNI.TagList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return flooJNI.TagList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    flooJNI.TagList_clear(swigCPtr, this);
  }

  public void add(String x) {
    flooJNI.TagList_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return flooJNI.TagList_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    flooJNI.TagList_set(swigCPtr, this, i, val);
  }

}
